import { Header } from "@/components/header"
import { Footer } from "@/components/footer"

import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms and conditions for using the NoReply consumer advocacy platform. Read our terms of service, user agreement, and acceptable use policy.",
  robots: {
    index: true,
    follow: true,
  },
  openGraph: {
    title: "Terms of Service | NoReply",
    description: "Terms and conditions for using the NoReply consumer advocacy platform.",
    type: "website",
  },
}

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Header />

      <main className="flex-1">
        <div className="container mx-auto px-4 py-16 md:py-24">
          <div className="max-w-3xl mx-auto">
            <h1 className="text-4xl font-bold tracking-tight text-foreground font-display mb-4">
              Terms of Service
            </h1>
            <p className="text-muted-foreground mb-12">
              Last updated: December 2024
            </p>

            <div className="prose prose-forest max-w-none space-y-8">
              <section>
                <h2 className="text-2xl font-semibold text-foreground font-display mb-4">
                  1. Agreement to Terms
                </h2>
                <p className="text-muted-foreground mb-4">
                  By accessing or using NoReply (&ldquo;the Service&rdquo;), you agree to be bound by these Terms of Service.
                  If you disagree with any part of these terms, you may not use our Service.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground font-display mb-4">
                  2. Description of Service
                </h2>
                <p className="text-muted-foreground mb-4">
                  NoReply is an AI-powered platform that helps consumers create professional complaint letters.
                  Our Service includes:
                </p>
                <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                  <li>AI-assisted complaint letter generation</li>
                  <li>Research on applicable consumer protection laws</li>
                  <li>Company contact information lookup</li>
                  <li>Evidence organization tools</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground font-display mb-4">
                  3. Important Disclaimers
                </h2>
                <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 mb-4">
                  <p className="text-amber-900 font-medium mb-2">Not Legal Advice</p>
                  <p className="text-amber-800 text-sm">
                    NoReply is not a law firm and does not provide legal advice. The information and letters
                    generated by our Service are for informational purposes only and should not be construed
                    as legal advice. For specific legal matters, consult a qualified solicitor or legal professional.
                  </p>
                </div>
                <div className="space-y-4 text-muted-foreground">
                  <p>
                    <strong className="text-foreground">No Guarantee of Results:</strong> While we strive to provide accurate
                    information and effective complaint letters, we cannot guarantee any specific outcome from your complaint.
                    Results depend on many factors outside our control.
                  </p>
                  <p>
                    <strong className="text-foreground">AI-Generated Content:</strong> Our AI systems may occasionally produce
                    inaccurate information. You should review all generated content before sending and verify any legal
                    references independently.
                  </p>
                </div>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground font-display mb-4">
                  4. User Responsibilities
                </h2>
                <p className="text-muted-foreground mb-4">When using our Service, you agree to:</p>
                <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                  <li>Provide accurate and truthful information about your complaints</li>
                  <li>Not use the Service for fraudulent, harassing, or illegal purposes</li>
                  <li>Not attempt to manipulate or abuse our AI systems</li>
                  <li>Review all generated content before sending to third parties</li>
                  <li>Keep your account credentials secure</li>
                  <li>Comply with all applicable laws and regulations</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground font-display mb-4">
                  5. Account Terms
                </h2>
                <div className="space-y-4 text-muted-foreground">
                  <p>
                    You must be at least 18 years old to use this Service. You are responsible for maintaining
                    the security of your account and password. We cannot and will not be liable for any loss or
                    damage from your failure to comply with this security obligation.
                  </p>
                  <p>
                    You may not use the Service for any illegal or unauthorized purpose. You must not violate
                    any laws in your jurisdiction when using the Service.
                  </p>
                </div>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground font-display mb-4">
                  6. Subscription and Payment
                </h2>
                <div className="space-y-4 text-muted-foreground">
                  <p>
                    <strong className="text-foreground">Free Tier:</strong> We offer a free tier with limited features.
                    No payment information is required for the free tier.
                  </p>
                  <p>
                    <strong className="text-foreground">Paid Subscriptions:</strong> Paid plans are billed monthly or annually.
                    You authorize us to charge your payment method on a recurring basis until you cancel.
                  </p>
                  <p>
                    <strong className="text-foreground">Cancellation:</strong> You may cancel your subscription at any time.
                    Cancellation takes effect at the end of your current billing period. No refunds are provided for
                    partial billing periods.
                  </p>
                  <p>
                    <strong className="text-foreground">Price Changes:</strong> We reserve the right to change our prices.
                    We will notify you at least 30 days before any price increase takes effect.
                  </p>
                </div>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground font-display mb-4">
                  7. Intellectual Property
                </h2>
                <div className="space-y-4 text-muted-foreground">
                  <p>
                    <strong className="text-foreground">Our Content:</strong> The Service and its original content, features,
                    and functionality are owned by NoReply and are protected by copyright, trademark, and other laws.
                  </p>
                  <p>
                    <strong className="text-foreground">Your Content:</strong> You retain ownership of all content you submit
                    to the Service. By submitting content, you grant us a license to use it to provide and improve our Service.
                  </p>
                  <p>
                    <strong className="text-foreground">Generated Letters:</strong> Letters generated by our Service are yours
                    to use. You may copy, send, and modify them as needed for your complaints.
                  </p>
                </div>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground font-display mb-4">
                  8. Limitation of Liability
                </h2>
                <p className="text-muted-foreground mb-4">
                  To the maximum extent permitted by law, NoReply shall not be liable for any indirect, incidental,
                  special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred
                  directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from:
                </p>
                <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                  <li>Your use or inability to use the Service</li>
                  <li>Any conduct or content of any third party on the Service</li>
                  <li>Any content obtained from the Service</li>
                  <li>Unauthorized access, use, or alteration of your content</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground font-display mb-4">
                  9. Termination
                </h2>
                <p className="text-muted-foreground mb-4">
                  We may terminate or suspend your account and access to the Service immediately, without prior notice
                  or liability, for any reason, including breach of these Terms. Upon termination, your right to use
                  the Service will immediately cease.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground font-display mb-4">
                  10. Changes to Terms
                </h2>
                <p className="text-muted-foreground mb-4">
                  We reserve the right to modify these terms at any time. We will provide notice of material changes
                  by posting the new Terms on this page and updating the &ldquo;Last updated&rdquo; date. Your continued use
                  of the Service after any changes constitutes acceptance of the new Terms.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground font-display mb-4">
                  11. Governing Law
                </h2>
                <p className="text-muted-foreground mb-4">
                  These Terms shall be governed by and construed in accordance with the laws of England and Wales,
                  without regard to conflict of law provisions. Any disputes arising from these Terms or your use
                  of the Service shall be subject to the exclusive jurisdiction of the courts of England and Wales.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground font-display mb-4">
                  12. Contact Us
                </h2>
                <p className="text-muted-foreground">
                  If you have any questions about these Terms, please contact us at{" "}
                  <a href="mailto:legal@usenoreply.com" className="text-forest-600 hover:underline">
                    legal@usenoreply.com
                  </a>
                </p>
              </section>
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  )
}
